### PR TITLE
Changes for emscripten

### PR DESCRIPTION
**Pull request by MarkMcCaskey**

### CODE REVIEW

**Comment by MarkMcCaskey** [comment]
Oops, sorry this is not meant to go here!

**Comment by mbbill** [comment]
no problem :)
By the way, recently I'm working on a new feature, which might make this project a bit useful.
The short term goal is to allow jsc.js compile Javascript into JSC's low level interpreter's bytecode, and later run with bytecode only. It might be useful for places where code protection requirements is high.
Since JSC.js compiles JavaScript, and therefore can run without original source code, so the security level is much higher than an obfuscator.
Looks like you guys are working on it, I'd like to know your thoughts

**Comment by mbbill** [comment]
it can be seen as another approach of "compiling JavaScript into WebAssembly"

**Comment by syrusakbary** [comment]
Completely. The compilation of JS to WebAssembly is a super interesting idea.

The approach of trying to reconstruct WebAssembly from js-compiled bytecode is also something similar of what this project is trying to do: https://github.com/esmbly/esmbly

We are eager to see how this idea evolves!

**Pull request closed without merging**
